salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/RiggohAdminConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Riggoh Admin Settings. Do not Edit it directly!</description>
    <label>Riggoh Admin Config</label>
</CustomObject>

salesforce-integration/Salesforce-Components/objects/RiggohAdminConfig__c/fields/Attach_Report_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Attach_Report_To_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should we save generated report to External system: OneDrive etc.</description>
    <inlineHelpText>Should we save generated report to External system: OneDrive etc.</inlineHelpText>
    <label>Attach Report To Email</label>
    <type>Checkbox</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/fields/Email_For_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Email_For_Reporting__c</fullName>
    <description>This email will be used to get scheduler reports.</description>
    <inlineHelpText>This email will be used to get scheduler reports.</inlineHelpText>
    <label>Email For Reporting</label>
    <type>Email</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/fields/Report_Range__c.field-meta.xml
<CustomField>
    <fullName>Report_Range__c</fullName>
    <description>Report Range: Week</description>
    <inlineHelpText>Report Range: Week</inlineHelpText>
    <label>Report Range</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/fields/Run_Day__c.field-meta.xml
<CustomField>
    <fullName>Run_Day__c</fullName>
    <description>0- Sunday, 1 - Monday, ....</description>
    <inlineHelpText>0- Sunday, 1 - Monday, ....</inlineHelpText>
    <label>Run Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-integration/Salesforce-Components/objects/RiggohAdminConfig__c/fields/Save_To_External__c.field-meta.xml
<CustomField>
    <fullName>Save_To_External__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should we save generated report to External system: OneDrive etc.</description>
    <inlineHelpText>Should we save generated report to External system: OneDrive etc.</inlineHelpText>
    <label>Save To External</label>
    <type>Checkbox</type>
</CustomField>

salesforce-integration/Salesforce Components/classes/RiggohAdminTest.cls
/**
 * Created by Viktor S. Yaremenko on 4/17/2019.
 */

@IsTest
private class RiggohAdminTest {

    @IsTest(SeeAllData=true)
    static void testChainalyticsDataBase() {
        ChainalyticsDataBase.generateReport(Date.today(), Date.today().addDays(-7));
    }

    @IsTest(SeeAllData=true)
    static void testDATExportBase() {
        DATExportBase.generateReport(Date.today(), Date.today().addDays(-7));
    }

    static testMethod void testRiggohAdminCtrl() {
        RiggohAdminCtrl ctrl = new RiggohAdminCtrl();

        ctrl.chaina_rangeEnd = Date.today();
        ctrl.chaina_rangeStart = ctrl.chaina_rangeEnd.addDays(-30);

        ctrl.chaina_setCron();
        ctrl.getchaina_CurrentCronState();
        ctrl.chaina_getReport();
        ctrl.chaina_resetToDefault();

        ctrl.dat_rangeEnd = Date.today();
        ctrl.dat_rangeStart = ctrl.chaina_rangeEnd.addDays(-30);

        ctrl.dat_setCron();
        ctrl.getdat_CurrentCronState();
        ctrl.dat_getReport();
        ctrl.dat_resetToDefault();


        RiggohAdminConfig__c chaina = new RiggohAdminConfig__c(
                Name = ChainalyticsDataBase.CONFIG_KEY,
                Attach_Report_To_Email__c = false,
                Email_For_Reporting__c = UserInfo.getUserEmail(),
                Report_Range__c = 'week',
                Run_Day__c = 1, //sunday
                Save_To_External__c = true
        );
        insert chaina;

        RiggohAdminConfig__c dat = new RiggohAdminConfig__c(
                Name = DATExportBase.CONFIG_KEY,
                Attach_Report_To_Email__c = false,
                Email_For_Reporting__c = UserInfo.getUserEmail(),
                Report_Range__c = 'week',
                Run_Day__c = 1, //sunday
                Save_To_External__c = true
        );
        insert dat;

        Test.startTest();
        String chaina_jobId = System.schedule('testChainalyticsDataScheduler', '0 0 0 3 9 ? 2022', new ChainalyticsDataScheduler());
        CronTrigger chaina_ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :chaina_jobId];
        System.assertEquals('0 0 0 3 9 ? 2022', chaina_ct.CronExpression);
        System.assertEquals(0, chaina_ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(chaina_ct.NextFireTime));

        String dat_jobId = System.schedule('testDATExportScheduler', '0 0 0 3 9 ? 2022', new DATExportScheduler());
        CronTrigger dat_ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :dat_jobId];
        System.assertEquals('0 0 0 3 9 ? 2022', dat_ct.CronExpression);
        System.assertEquals(0, dat_ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(dat_ct.NextFireTime));

        Test.stopTest();
    }

}