salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/RiggohAdminConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Riggoh Admin Settings. Do not Edit it directly!</description>
    <label>Riggoh Admin Config</label>
</CustomObject>

salesforce-integration/Salesforce-Components/objects/RiggohAdminConfig__c/fields/Attach_Report_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Attach_Report_To_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should we save generated report to External system: OneDrive etc.</description>
    <inlineHelpText>Should we save generated report to External system: OneDrive etc.</inlineHelpText>
    <label>Attach Report To Email</label>
    <type>Checkbox</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/fields/Email_For_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Email_For_Reporting__c</fullName>
    <description>This email will be used to get scheduler reports.</description>
    <inlineHelpText>This email will be used to get scheduler reports.</inlineHelpText>
    <label>Email For Reporting</label>
    <type>Email</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/RiggohAdminConfig__c/fields/Report_Range__c.field-meta.xml
<CustomField>
    <fullName>Report_Range__c</fullName>
    <description>Report Range: Week</description>
    <inlineHelpText>Report Range: Week</inlineHelpText>
    <label>Report Range</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-integration/Salesforce-Components/objects/RiggohAdminConfig__c/fields/Save_To_External__c.field-meta.xml
<CustomField>
    <fullName>Save_To_External__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should we save generated report to External system: OneDrive etc.</description>
    <inlineHelpText>Should we save generated report to External system: OneDrive etc.</inlineHelpText>
    <label>Save To External</label>
    <type>Checkbox</type>
</CustomField>

salesforce-integration/Salesforce-Components/QA/force-app/main/default/classes/ChainalyticsDataScheduler.cls
/**
 * Created by Viktor S. Yaremenko on 11/10/2018.
 */

global class ChainalyticsDataScheduler implements Schedulable {

    global void execute(SchedulableContext SC) {
        RiggohAdminConfig__c chaina = RiggohAdminConfig__c.getValues(ChainalyticsDataBase.CONFIG_KEY);
        if (chaina == null) {
            throw new ChainalyticsDataBase.ChainalyticsDataBaseException(ChainalyticsDataBase.CONFIG_KEY + ' is empty.');
        }
        Boolean isCronSendEmail = chaina.Attach_Report_To_Email__c;
        Boolean isCronSaveToOne = chaina.Save_To_External__c;
        String cronEmailAddress = String.isNotBlank(chaina.Email_For_Reporting__c) ?
                chaina.Email_For_Reporting__c : UserInfo.getUserEmail();
        //cronRangeDays = 7; //Report_Range__c = 'week
        Date rangeEnd = Date.today().addDays(-1);
        Date rangeStart = Date.today().addDays(-7);
        String docId = ChainalyticsDataBase.generateReport(rangeStart, rangeEnd);

        if (!Test.isRunningTest()) {
            if (String.isNotBlank(docId) && isCronSaveToOne) {
                ChainalyticsDataBase.sendToOneDriveAsync(docId);
            }
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new List<String>{
                    cronEmailAddress
            });
            mail.setSubject('ChainalyticsDataScheduler Report');
            if (isCronSendEmail) {
                mail.setEntityAttachments(new List<String>{
                        docId
                });
            }
            if (String.isNotBlank(docId)) {
                String docURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + docId;
                mail.setHtmlBody('<p>ChainalyticsDataScheduler done.</p><p>Document link: ' + docURL + '</p>');
            }
            mail.setPlainTextBody('ChainalyticsDataScheduler done.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    mail
            });
        }
    }
}