salesforce-integration/Salesforce Components/objects/Marketplace_Exposed_Data__c/Marketplace_Exposed_Data__c.object-meta.xml
<CustomObject>
    <label>Marketplace Exposed Data</label>
    <nameField>
        <displayFormat>MEI-{000000000}</displayFormat>
        <label>Marketplace Exposed Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketplace Exposed Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-integration/Salesforce Components/objects/Marketplace_Exposed_Data__c/fields/extSysId__c.field-meta.xml
<CustomField>
    <fullName>extSysId__c</fullName>
    <label>extSysId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-integration/Salesforce Components/objects/Marketplace_Exposed_Data__c/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <label>Load</label>
    <referenceTo>rtms__Load__c</referenceTo>
    <relationshipLabel>Marketplace Exposed Data</relationshipLabel>
    <relationshipName>Marketplace_Exposed_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-integration/Salesforce-Components/objects/Marketplace_Exposed_Data__c/fields/Marketplace_Exposed_Id__c.field-meta.xml
<CustomField>
    <fullName>Marketplace_Exposed_Id__c</fullName>
    <externalId>true</externalId>
    <label>Marketplace Exposed Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-integration/Salesforce-Components/classes/GetMarketPlaceDetails.cls
public class GetMarketPlaceDetails {
    public static WrapperClassForAPI.WrapperforMarketPlac getMarketPlaceDetails(String LoadId,string triggerAction){
        
        string marketplaceId = '';
        List<Marketplace_Exposed_Data__c> marketPlaceList = [select id,Marketplace_Exposed_Id__c,extSysId__c from Marketplace_Exposed_Data__c where Load__c =:LoadId limit 1];
        
        List<rtms__Load__c> ListOfLoead =[Select Id, createdDate from rtms__Load__c where ID =:LoadId];
        
        if(marketPlaceList!= null && marketPlaceList.size() > 0 ){
            system.debug('---if----10');
            marketplaceId = marketPlaceList[0].Marketplace_Exposed_Id__c;
            WrapperClassForAPI.WrapperforMarketPlac wrapp = new WrapperClassForAPI.WrapperforMarketPlac();
            wrapp.marketplaceId = marketPlaceList[0].Marketplace_Exposed_Id__c;
            wrapp.extSysId = marketPlaceList[0].extSysId__c;
            wrapp.isMarketplaceIdAvailable = true;
            return wrapp;
        }else{
            if((marketplaceId == null || marketplaceId == '') && ListOfLoead != null && ListOfLoead.size() > 0){
                Integer decMinutes = Integer.valueof((((system.now().getTime())/1000/60) - (ListOfLoead[0].createdDate.getTime())/1000/60));
                system.debug('---decMinutes'+decMinutes);
                system.debug('--triggerAction---'+triggerAction);
         
                if(decMinutes < 5 && (triggerAction != 'Insert Batch' && triggerAction != 'Update Batch')){
                    system.debug('---decMinutes'+decMinutes); 
                     WrapperClassForAPI.WrapperforMarketPlac wrapp = new WrapperClassForAPI.WrapperforMarketPlac();
                    wrapp.marketplaceId = '';
                    wrapp.extSysId = '';
                    wrapp.isMarketplaceIdAvailable = false;
                    return wrapp;
                } 
            } 
        }
        
        
        return null;
    }
    
}